import NextThemeProvider from "@/lib/Providers/NextThemeProvider";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // data-theme="light"
      className={`${roboto.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <NextThemeProvider>
          <main>{children}</main>
        </NextThemeProvider>

        <Toaster />
      </body>
    </html>
  );
}
